version: '3'
services:
  app:
    build: back
    links:
      - "mysql_db:db"
  front:
    build: front
    ports:
      - "8088:8088"
  mysql_db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWOR: example
    ports:
      - "3306:3306"
    volumes:
      - ./back/db:/docker-entrypoint-initdb.d
